# Generated by Django 4.0.2 on 2022-03-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_created_remove_project_demo_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
