# Generated by Django 4.0.2 on 2022-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
